---
deployment:
  tasks:
    - export DEPLOYPATH=/home/regiuzkk/public_html/
    - export BETAPATH=/home/regiuzkk/beta.helphog.com/
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -r * $DEPLOYPATH
    - /bin/cp /home/regiuzkk/stripe-api-keys/live/stripe.json $DEPLOYPATH/php
    - /bin/cp /home/regiuzkk/stripe-api-keys/live/keys.js $DEPLOYPATH/js
    - /bin/rm -rf $BETAPATH/*
    - /bin/cp -r * $BETAPATH
    - /bin/cp /home/regiuzkk/stripe-api-keys/test/stripe.json $BETAPATH/php
    - /bin/cp /home/regiuzkk/stripe-api-keys/test/keys.js $BETAPATH/js
    - /bin/chmod $DEPLOYPATH/php/stripe.json 600
