---
deployment:
  tasks:
    - export DEPLOYPATH=/home/regiuzkk/public_html/
    - export BETAPATH=/home/regiuzkk/beta.helphog.com/
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -r * $DEPLOYPATH
    - /bin/cp /home/regiuzkk/stripe-api-keys/live/stripe.json $DEPLOYPATH
    - /bin/rm -rf $BETAPATH/*
    - /bin/cp -r * $BETAPATH
    - /bin/cp /home/regiuzkk/stripe-api-keys/test/stripe.json $BETAPATH
