-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgfhPDbDW4hrbjdD8H
HyCizHoLguCY86iTWvcwNOx9/oKgCgYIKoZIzj0DAQehRANCAAQFbYd/mjahgGl0
J8CI4O+V9Gjcf8kTgGkohmASEsOGTzBWNqQp8k+G5v+6fV5BJ70wTBXT1Dq1ldk4
4sMTNvkL
-----END PRIVATE KEY-----